# Generated by Django 2.1.4 on 2018-12-23 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_item', models.CharField(max_length=255)),
                ('type_item', models.CharField(max_length=255)),
                ('name_item', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('cdUPC', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'items',
                'db_table': 'items',
                'ordering': ['name_item'],
                'managed': False,
            },
        ),
    ]
