# Generated by Django 2.1.4 on 2018-12-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateField(verbose_name='Date Purchased')),
                ('count', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Count')),
                ('cost_per_item', models.DecimalField(decimal_places=4, default=0.0, max_digits=11, verbose_name='Cost per Item')),
                ('total_cost_items', models.DecimalField(decimal_places=4, default=0.0, max_digits=11, verbose_name='Total Cost of Items')),
                ('amt_discount', models.DecimalField(decimal_places=4, default=0.0, max_digits=11, verbose_name='Discount Amount')),
                ('perc_rate_sales_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Sales Tax Rate %')),
                ('amt_sales_tax', models.DecimalField(decimal_places=4, default=0.0, max_digits=11, verbose_name='Sales Tax Amount')),
                ('cost_total', models.DecimalField(decimal_places=4, default=0.0, max_digits=11, verbose_name='Total Cost')),
            ],
            options={
                'verbose_name_plural': 'lists',
                'db_table': 'lists',
                'ordering': ['-date_purchased', 'supplier', 'item'],
                'managed': False,
            },
        ),
    ]
